development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tcc_puts_development
  pool: 5
  username: root
  password: admin
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tcc_puts_test
  pool: 5
  username: root
  password: admin
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tcc_puts_production
  pool: 5
  username: root
  password: admin
  socket: /tmp/mysql.sock
